openapi: 3.1.0
info:
  version: 1.0.0
  title: Contact App
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  contact:
    name: Kateryna Frolova
    email: froyzend1993@gmail.com

tags:
  - name: Contacts
    description: Contacts operations

servers:
  - url: https://nodejs-hw-mongodb-v2o8.onrender.com
  - url: http://localhost:3000

paths:
  /contacts:
    get:
      $ref: ../swagger/paths/contacts/get.yaml
    post:
      $ref: ../swagger/paths/contacts/post.yaml
  /contacts/{id}:
    patch:
      $ref: ../swagger/paths/contacts/{id}/patch.yaml
    delete:
      $ref: ../swagger/paths/contacts/{id}/delete.yaml

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
